<!-- JavaScript Files -->
<script src="/scripts/jquery-1.11.3.min.js"></script>

<!-- Bootstrap must come before jQuery UI to prevent missing images -->
<script src="/scripts/bootstrap.min.js"></script>
<script type='text/javascript'>
	$.fn.bsbutton = $.fn.button.noConflict();
	$.fn.bstooltip = $.fn.tooltip.noConflict();
</script>
<script src="/lib/jquery/jquery-ui-1.10.4.custom/js/jquery-ui-1.10.4.custom.min.js"></script>
<script src="/lib/jquery/plugins/jquery.fileupload.js"></script>
<script src="/lib/gca/gca.js" type="text/javascript"></script>
<script src="/lib/gca/gca.photo.js" type="text/javascript"></script>
